import { z } from "zod";

import { vaultService } from "../vault";
import {
  checkPostizApprovedDispatchHealth,
  checkPostizProviderHealth,
  type ProviderEnvironment,
} from "./provider-health";

/**
 * Server-only Postiz public-API adapter.
 *
 * It accepts one immutable, individually approved scheduling snapshot at a
 * time. It deliberately does not manage account passwords, browser sessions,
 * proxies, account creation, bulk engagement, DMs, or an unapproved content
 * calendar. The Trigger worker imports the selected render into Postiz first,
 * then schedules that Postiz-owned upload exactly once.
 */
const POSTIZ_PUBLIC_API_PATH = "/public/v1";
const POSTIZ_VAULT_URL_KEY = "POSTIZ_URL";
const POSTIZ_VAULT_API_KEY = "POSTIZ_API_KEY";
/** Do not hand Postiz a near-due schedule that could be treated as immediate. */
export const POSTIZ_MINIMUM_SCHEDULE_LEAD_TIME_MS = 60_000;

const SafeIdentifierSchema = z
  .string()
  .trim()
  .min(1)
  .max(240)
  .regex(/^[A-Za-z0-9][A-Za-z0-9._:-]*$/);
const IsoDateTimeSchema = z.string().datetime({ offset: true });
const CaptionSchema = z.string().trim().min(1).max(5_000);
const MediaTypeSchema = z.enum(["image", "video"]);

export const PostizProviderSchema = z.enum([
  "x",
  "instagram",
  "instagram-standalone",
  "tiktok",
  "youtube",
  "pinterest",
  "facebook",
  "threads",
  "linkedin",
  "bluesky",
]);
export type PostizProvider = z.infer<typeof PostizProviderSchema>;

/** A safe, user-facing block rather than a guessed provider setting. */
export class PostizScheduleBlockedError extends Error {
  override name = "PostizScheduleBlockedError";
}

function block(message: string): never {
  throw new PostizScheduleBlockedError(message);
}

function unsafeHost(hostname: string): boolean {
  const host = hostname.toLowerCase().replace(/^\[|\]$/g, "");
  return (
    host === "localhost" ||
    host.endsWith(".localhost") ||
    host.endsWith(".local") ||
    host === "::1" ||
    host === "0.0.0.0" ||
    /^127\./.test(host) ||
    /^10\./.test(host) ||
    /^192\.168\./.test(host) ||
    /^169\.254\./.test(host) ||
    /^0\./.test(host) ||
    /^172\.(?:1[6-9]|2\d|3[01])\./.test(host) ||
    /^fc[0-9a-f]{2}:/i.test(host) ||
    /^fd[0-9a-f]{2}:/i.test(host) ||
    /^fe80:/i.test(host)
  );
}

/**
 * A Postiz endpoint must be a clean public HTTPS origin. Credentials, paths,
 * query strings, and fragments would make a deployment secret ambiguous.
 */
export function cleanPostizOrigin(value: string): string {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    block("Postiz URL is invalid");
  }
  if (
    url.protocol !== "https:" ||
    url.username ||
    url.password ||
    url.search ||
    url.hash ||
    (url.pathname !== "" && url.pathname !== "/") ||
    unsafeHost(url.hostname)
  ) {
    block("Postiz URL must be a clean public HTTPS origin");
  }
  return url.origin;
}

/**
 * The only source URL passed to Postiz is generated by the Media Engine worker
 * for a controlled R2 object. Query parameters are permitted because an R2
 * signed URL needs them; credentials, fragments, private hosts, and non-HTTPS
 * origins are not.
 */
export function validatePostizUploadSourceUrl(value: string): string {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    block("approved Postiz media URL is invalid");
  }
  if (
    url.protocol !== "https:" ||
    url.username ||
    url.password ||
    url.hash ||
    unsafeHost(url.hostname)
  ) {
    block("approved Postiz media URL is unsafe");
  }
  return url.toString();
}

function validatePostizUploadedAssetUrl(value: string): string {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    block("Postiz returned an invalid uploaded media path");
  }
  if (
    url.protocol !== "https:" ||
    url.username ||
    url.password ||
    url.search ||
    url.hash ||
    unsafeHost(url.hostname)
  ) {
    block("Postiz returned an unsafe uploaded media path");
  }
  return url.toString();
}

const XReplyAudienceSchema = z.enum([
  "everyone",
  "following",
  "mentionedUsers",
  "subscribers",
  "verified",
]);

/** Social-account platforms that can be bound to a supported Postiz channel. */
export const PostizBoundAccountPlatformSchema = z.enum([
  "instagram",
  "tiktok",
  "youtube",
  "pinterest",
  "x",
  "facebook",
  "threads",
  "linkedin",
  "bluesky",
]);
export type PostizBoundAccountPlatform = z.infer<typeof PostizBoundAccountPlatformSchema>;

const CreatorContentFormatSchema = z.enum([
  "image",
  "carousel",
  "reel",
  "story",
  "short",
  "text",
]);

/**
 * The schedule-request descriptor is deliberately Media Engine-shaped. It is
 * frozen into the action snapshot, then mapped to Postiz's documented wire
 * names only inside this server-only adapter.
 */
const XScheduleSettingsInputSchema = z
  .object({
    __type: z.literal("x"),
    replyAudience: XReplyAudienceSchema,
    madeWithAi: z.boolean(),
    paidPartnership: z.boolean(),
  })
  .strict();

const InstagramScheduleSettingsInputSchema = z.object({ __type: z.literal("instagram") }).strict();
const InstagramStandaloneScheduleSettingsInputSchema = z.object({ __type: z.literal("instagram-standalone") }).strict();

const TikTokScheduleSettingsInputSchema = z
  .object({
    __type: z.literal("tiktok"),
    privacyLevel: z.enum([
      "PUBLIC_TO_EVERYONE",
      "MUTUAL_FOLLOW_FRIENDS",
      "FOLLOWER_OF_CREATOR",
      "SELF_ONLY",
    ]),
    duet: z.boolean(),
    stitch: z.boolean(),
    comments: z.boolean(),
    autoAddMusic: z.enum(["yes", "no"]),
    brandContent: z.boolean(),
    brandOrganic: z.boolean(),
    videoMadeWithAi: z.boolean(),
    /** UPLOAD only creates an app inbox draft, never a scheduled profile post. */
    contentPostingMethod: z.literal("DIRECT_POST"),
  })
  .strict();

const YouTubeScheduleSettingsInputSchema = z
  .object({
    __type: z.literal("youtube"),
    visibility: z.enum(["public", "unlisted", "private"]),
    madeForKids: z.enum(["yes", "no"]),
  })
  .strict();

const PinterestScheduleSettingsInputSchema = z
  .object({
    __type: z.literal("pinterest"),
    board: SafeIdentifierSchema,
  })
  .strict();

const FacebookScheduleSettingsInputSchema = z.object({ __type: z.literal("facebook") }).strict();
const ThreadsScheduleSettingsInputSchema = z.object({ __type: z.literal("threads") }).strict();
const LinkedInScheduleSettingsInputSchema = z.object({ __type: z.literal("linkedin") }).strict();
const BlueskyScheduleSettingsInputSchema = z.object({ __type: z.literal("bluesky") }).strict();

export const PostizScheduleSettingsInputSchema = z.discriminatedUnion("__type", [
  XScheduleSettingsInputSchema,
  InstagramScheduleSettingsInputSchema,
  InstagramStandaloneScheduleSettingsInputSchema,
  TikTokScheduleSettingsInputSchema,
  YouTubeScheduleSettingsInputSchema,
  PinterestScheduleSettingsInputSchema,
  FacebookScheduleSettingsInputSchema,
  ThreadsScheduleSettingsInputSchema,
  LinkedInScheduleSettingsInputSchema,
  BlueskyScheduleSettingsInputSchema,
]);
export type PostizScheduleSettingsInput = z.infer<typeof PostizScheduleSettingsInputSchema>;

/** Raw Postiz v1 settings emitted by this adapter, after the above mapping. */
const XSettingsSchema = z
  .object({
    __type: z.literal("x"),
    who_can_reply_post: XReplyAudienceSchema,
    made_with_ai: z.boolean(),
    paid_partnership: z.boolean(),
  })
  .strict();

const InstagramSettingsSchema = z
  .object({
    __type: z.literal("instagram"),
    post_type: z.enum(["post", "story"]),
  })
  .strict();

const InstagramStandaloneSettingsSchema = z
  .object({
    __type: z.literal("instagram-standalone"),
    post_type: z.enum(["post", "story"]),
  })
  .strict();

const TikTokSettingsSchema = z
  .object({
    __type: z.literal("tiktok"),
    title: z.string().trim().min(1).max(90),
    privacy_level: z.enum([
      "PUBLIC_TO_EVERYONE",
      "MUTUAL_FOLLOW_FRIENDS",
      "FOLLOWER_OF_CREATOR",
      "SELF_ONLY",
    ]),
    duet: z.boolean(),
    stitch: z.boolean(),
    comment: z.boolean(),
    autoAddMusic: z.enum(["yes", "no"]),
    brand_content_toggle: z.boolean(),
    brand_organic_toggle: z.boolean(),
    video_made_with_ai: z.boolean(),
    /** UPLOAD is not a scheduled profile post, so it is intentionally excluded. */
    content_posting_method: z.literal("DIRECT_POST"),
  })
  .strict();

const YouTubeSettingsSchema = z
  .object({
    __type: z.literal("youtube"),
    title: z.string().trim().min(2).max(100),
    type: z.enum(["public", "unlisted", "private"]),
    selfDeclaredMadeForKids: z.enum(["yes", "no"]),
  })
  .strict();

const PinterestSettingsSchema = z
  .object({
    __type: z.literal("pinterest"),
    board: SafeIdentifierSchema,
  })
  .strict();

const FacebookSettingsSchema = z.object({ __type: z.literal("facebook") }).strict();
const ThreadsSettingsSchema = z.object({ __type: z.literal("threads") }).strict();
const LinkedInSettingsSchema = z.object({ __type: z.literal("linkedin") }).strict();
const BlueskySettingsSchema = z.object({ __type: z.literal("bluesky") }).strict();

/**
 * The reviewed Postiz settings shapes that Media Engine can construct without
 * silently accepting provider-specific fields it does not understand.
 */
export const PostizProviderSettingsSchema = z.discriminatedUnion("__type", [
  XSettingsSchema,
  InstagramSettingsSchema,
  InstagramStandaloneSettingsSchema,
  TikTokSettingsSchema,
  YouTubeSettingsSchema,
  PinterestSettingsSchema,
  FacebookSettingsSchema,
  ThreadsSettingsSchema,
  LinkedInSettingsSchema,
  BlueskySettingsSchema,
]);
export type PostizProviderSettings = z.infer<typeof PostizProviderSettingsSchema>;

export const PostizApprovedScheduleSchema = z
  .object({
    actionId: SafeIdentifierSchema,
    idempotencyKey: z.string().trim().min(16).max(240),
    payloadHash: z.string().trim().min(1).max(240),
    connectionId: SafeIdentifierSchema,
    contentId: SafeIdentifierSchema,
    contentReviewVersion: z.number().int().positive(),
    integrationId: SafeIdentifierSchema,
    provider: PostizProviderSchema,
    /** Immutable Media Engine calendar instant in Unix milliseconds. */
    scheduledAt: z.number().int().positive(),
    title: z.string().trim().min(1).max(200),
    format: CreatorContentFormatSchema,
    caption: CaptionSchema,
    media: z.object({ assetKey: z.string().trim().min(1).max(1_024), mediaType: MediaTypeSchema }).strict(),
  })
  .strict();
export type PostizApprovedSchedule = z.infer<typeof PostizApprovedScheduleSchema>;

/**
 * Time is deliberately checked at the provider side-effect boundary rather
 * than while parsing the immutable snapshot. A completed action can therefore
 * be safely recognized as completed on a later Trigger replay, while a fresh
 * request that has become near-due still cannot be sent to Postiz.
 */
export function assertPostizScheduleIsSafelyFuture(
  input: PostizApprovedSchedule,
): PostizApprovedSchedule {
  const action = PostizApprovedScheduleSchema.parse(input);
  if (action.scheduledAt < Date.now() + POSTIZ_MINIMUM_SCHEDULE_LEAD_TIME_MS) {
    block("Postiz schedule time must be at least one minute in the future");
  }
  return action;
}

/** Minimal, sanitized evidence that Postiz accepted the frozen schedule. */
export const PostizScheduleProviderReceiptSchema = z
  .object({
    provider: z.literal("postiz"),
    postId: SafeIdentifierSchema,
    integrationId: SafeIdentifierSchema,
    /** The exact Unix-millisecond instant from the immutable snapshot. */
    scheduledAt: z.number().int().positive(),
  })
  .strict();
export type PostizScheduleProviderReceipt = z.infer<typeof PostizScheduleProviderReceiptSchema>;

export const PostizUploadedMediaSchema = z
  .object({
    id: SafeIdentifierSchema,
    path: z.string().trim().min(1).max(2_048),
  })
  .strict()
  .transform((value) => ({ ...value, path: validatePostizUploadedAssetUrl(value.path) }));
export type PostizUploadedMedia = z.infer<typeof PostizUploadedMediaSchema>;

const PostizSchedulePostSchema = z
  .object({
    integration: z.object({ id: SafeIdentifierSchema }).strict(),
    value: z
      .array(z.object({ content: CaptionSchema, image: z.array(PostizUploadedMediaSchema).length(1) }).strict())
      .length(1),
    settings: PostizProviderSettingsSchema,
  })
  .strict();

/** Exact documented v1 POST /public/v1/posts request body. */
export const PostizCreateScheduleRequestSchema = z
  .object({
    type: z.literal("schedule"),
    date: IsoDateTimeSchema,
    shortLink: z.literal(false),
    tags: z.array(z.never()).length(0),
    posts: z.array(PostizSchedulePostSchema).length(1),
  })
  .strict();
export type PostizCreateScheduleRequest = z.infer<typeof PostizCreateScheduleRequestSchema>;

export const PostizCreateScheduleResponseSchema = z
  .array(z.object({ postId: SafeIdentifierSchema, integration: SafeIdentifierSchema }).strict())
  .length(1);
export type PostizCreateScheduleResponse = z.infer<typeof PostizCreateScheduleResponseSchema>;

/** The list endpoint may grow fields; only these documented identity fields are used. */
const PostizIntegrationListSchema = z.array(
  z.object({
    id: SafeIdentifierSchema,
    identifier: z.string().trim().min(1).max(80),
    // The official list endpoint exposes these for an operator-facing channel
    // picker. Keep them optional so an older self-hosted Postiz instance can
    // still be reconciled by the scheduler, while discovery itself fails
    // closed only if its response is not safely parseable.
    name: z.string().trim().min(1).max(200).optional(),
    profile: z.string().trim().min(1).max(128).optional(),
    disabled: z.boolean(),
  }).passthrough(),
).max(500);

type FetchImplementation = typeof fetch;
type PostizVaultReader = typeof vaultService;

export type PostizCredentials = Readonly<{ origin: string; apiKey: string }>;

const POSTIZ_DISCOVERY_TIMEOUT_MS = 12_000;

/**
 * A deliberately small projection of the documented Postiz integration
 * response. The browser receives neither raw provider payloads, avatars,
 * organization metadata, API keys, nor OAuth material.
 */
export const PostizDiscoveredChannelSchema = z.object({
  id: SafeIdentifierSchema,
  provider: z.string().trim().min(1).max(80),
  platform: PostizBoundAccountPlatformSchema.optional(),
  handle: z.string().trim().min(1).max(128).optional(),
  displayLabel: z.string().trim().min(1).max(200),
  status: z.enum(["available", "disabled", "unsupported"]),
  capabilityHints: z.array(z.literal("schedule_content")).max(1),
  canMap: z.boolean(),
  mappingHint: z.string().trim().min(1).max(240),
}).strict();
export type PostizDiscoveredChannel = z.infer<typeof PostizDiscoveredChannelSchema>;

const POSTIZ_DISCOVERY_PLATFORM_BY_PROVIDER: Readonly<Record<string, PostizBoundAccountPlatform>> = {
  instagram: "instagram",
  "instagram-standalone": "instagram",
  tiktok: "tiktok",
  x: "x",
  facebook: "facebook",
  threads: "threads",
  pinterest: "pinterest",
  youtube: "youtube",
  linkedin: "linkedin",
  bluesky: "bluesky",
};

function compactPostizChannelText(value: string | undefined, maximum: number): string | undefined {
  if (!value) return undefined;
  const compact = value
    .replace(/[\u0000-\u001f\u007f]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, maximum);
  return compact || undefined;
}

function discoveredPostizChannel(integration: z.infer<typeof PostizIntegrationListSchema>[number]): PostizDiscoveredChannel {
  const provider = compactPostizChannelText(integration.identifier, 80)?.toLowerCase();
  if (!provider) block("Postiz channel discovery returned an invalid provider");
  const platform = POSTIZ_DISCOVERY_PLATFORM_BY_PROVIDER[provider];
  const handle = compactPostizChannelText(integration.profile, 128);
  const displayLabel = compactPostizChannelText(integration.name, 200) ?? handle ?? `${provider} channel`;
  const status = integration.disabled
    ? "disabled" as const
    : platform
      ? "available" as const
      : "unsupported" as const;
  const canMap = status === "available";
  const mappingHint = status === "disabled"
    ? "This Postiz channel is disabled. Re-enable it in Postiz before mapping."
    : status === "unsupported"
      ? "This Postiz provider is not in the governed Creator Promotions scheduling contract."
      : handle
        ? "Ready to map as an operator-attested channel. Scheduling still needs its own review and explicit handoff."
        : "Choose this channel, then confirm its account handle before mapping. Scheduling still needs its own review and explicit handoff.";
  return PostizDiscoveredChannelSchema.parse({
    id: integration.id,
    provider,
    platform,
    handle,
    displayLabel,
    status,
    capabilityHints: canMap ? ["schedule_content"] : [],
    canMap,
    mappingHint,
  });
}

/**
 * Credentials are resolved only in the server worker from the fixed `postiz`
 * Vault bucket. Media Engine's existing convention keeps social provider keys
 * out of the runtime environment, so there is intentionally no env fallback.
 */
export async function resolvePostizCredentials(
  env: ProviderEnvironment = process.env,
  readVault: PostizVaultReader = vaultService,
): Promise<PostizCredentials> {
  const health = checkPostizApprovedDispatchHealth(env);
  if (!health.canDispatchApprovedActions) {
    block("Postiz approved scheduling is not enabled or configured");
  }
  const credentials = await readVault("postiz");
  const apiKey = credentials[POSTIZ_VAULT_API_KEY]?.trim();
  if (!apiKey || apiKey.length < 16 || apiKey.length > 2_048) {
    block("Postiz API key is unavailable in the server vault");
  }
  const configuredUrl = credentials[POSTIZ_VAULT_URL_KEY]?.trim();
  if (!configuredUrl) block("Postiz URL is unavailable in the server vault");
  return { origin: cleanPostizOrigin(configuredUrl), apiKey };
}

/**
 * Read-only discovery has the same fixed vault boundary as scheduling but is
 * intentionally not gated by `CREATOR_POSTIZ_SCHEDULE_ENABLED`: an operator
 * must be able to inspect an already-authorized Postiz instance before any
 * scheduling capability is enabled. It still requires the strict server-only
 * resolver/dispatcher configuration and never falls back to browser input.
 */
export async function resolvePostizDiscoveryCredentials(
  env: ProviderEnvironment = process.env,
  readVault: PostizVaultReader = vaultService,
): Promise<PostizCredentials> {
  const health = checkPostizProviderHealth(env);
  if (health.status !== "ready") {
    block("Postiz channel discovery is not configured");
  }
  const credentials = await readVault("postiz");
  const apiKey = credentials[POSTIZ_VAULT_API_KEY]?.trim();
  if (!apiKey || apiKey.length < 16 || apiKey.length > 2_048) {
    block("Postiz API key is unavailable in the server vault");
  }
  const configuredUrl = credentials[POSTIZ_VAULT_URL_KEY]?.trim();
  if (!configuredUrl) block("Postiz URL is unavailable in the server vault");
  return { origin: cleanPostizOrigin(configuredUrl), apiKey };
}

/**
 * Read one sanitized list of channels on an explicit operator request. This
 * does not write to Postiz, persist a provider response, link an account, or
 * enable scheduling. The caller must still submit the chosen channel through
 * the existing governed `link-postiz-integration` flow.
 */
export async function discoverPostizChannels(args: {
  credentials?: PostizCredentials;
  env?: ProviderEnvironment;
  readVault?: PostizVaultReader;
  request?: FetchImplementation;
} = {}): Promise<PostizDiscoveredChannel[]> {
  const credentials = args.credentials ?? await resolvePostizDiscoveryCredentials(args.env, args.readVault);
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), POSTIZ_DISCOVERY_TIMEOUT_MS);
  let response: Response;
  try {
    response = await (args.request ?? fetch)(postizEndpoint(credentials, "/integrations"), {
      method: "GET",
      redirect: "error",
      headers: { authorization: credentials.apiKey },
      signal: controller.signal,
      cache: "no-store",
    });
  } catch {
    block("Postiz channel discovery could not reach the configured server");
  } finally {
    clearTimeout(timeout);
  }
  if (!response!.ok) {
    // Consume and discard an error body so it cannot become an operator-facing
    // raw provider payload through a future wrapper or logger.
    await response!.text().catch(() => undefined);
    throw new Error(`Postiz channel discovery returned HTTP ${response!.status}`);
  }
  const body = await response!.json().catch(() => undefined);
  let integrations: z.infer<typeof PostizIntegrationListSchema>;
  try {
    integrations = PostizIntegrationListSchema.parse(body);
  } catch {
    block("Postiz channel discovery returned an invalid response");
  }
  return integrations
    .map(discoveredPostizChannel)
    .sort((left, right) => left.displayLabel.localeCompare(right.displayLabel) || left.id.localeCompare(right.id));
}

/**
 * Instagram has two official Postiz channel identifiers under one Media Engine
 * account platform. Every other supported platform must match exactly.
 */
export function postizProviderForBoundAccount(args: {
  platform: PostizBoundAccountPlatform;
  settings: unknown;
}): PostizProvider {
  const platform = PostizBoundAccountPlatformSchema.parse(args.platform);
  const settings = PostizScheduleSettingsInputSchema.parse(args.settings);
  if (platform === "instagram") {
    if (settings.__type === "instagram" || settings.__type === "instagram-standalone") {
      return settings.__type;
    }
    block("Postiz Instagram settings do not match the connected account");
  }
  if (settings.__type !== platform) {
    block("Postiz settings do not match the connected account platform");
  }
  return settings.__type;
}

function titleForProvider(title: string, provider: string, maximum: number, minimum = 1): string {
  const normalized = title.trim();
  if (normalized.length < minimum || normalized.length > maximum) {
    block(`approved ${provider} title is outside its supported length`);
  }
  return normalized;
}

function instagramPostType(action: PostizApprovedSchedule): "post" | "story" {
  switch (action.format) {
    case "story":
      return "story";
    case "image":
      if (action.media.mediaType !== "image") {
        block("Postiz Instagram image posts require image media");
      }
      return "post";
    case "reel":
    case "short":
      if (action.media.mediaType !== "video") {
        block("Postiz Instagram reels require video media");
      }
      return "post";
    case "carousel":
      block("Postiz Instagram carousel scheduling requires multiple approved assets");
    default:
      block("Postiz Instagram does not support this approved content format");
  }
}

function assertTikTokMediaCompatibility(action: PostizApprovedSchedule): void {
  // Postiz can express photo-specific TikTok options, but this first governed
  // worker has one approved rendered asset and the backend freezes TikTok
  // schedules only for video renders. Keeping that boundary narrow avoids
  // silently discarding video-only disclosures on photo delivery.
  if (action.media.mediaType !== "video") {
    block("Postiz TikTok direct scheduling requires approved video media");
  }
}

function settingsForProvider(
  action: PostizApprovedSchedule,
  raw: PostizScheduleSettingsInput,
): PostizProviderSettings {
  if (raw.__type !== action.provider) {
    block("Postiz provider settings do not match the approved integration");
  }
  switch (raw.__type) {
    case "x":
      return XSettingsSchema.parse({
        __type: "x",
        who_can_reply_post: raw.replyAudience,
        made_with_ai: raw.madeWithAi,
        paid_partnership: raw.paidPartnership,
      });
    case "instagram":
      return InstagramSettingsSchema.parse({ __type: "instagram", post_type: instagramPostType(action) });
    case "instagram-standalone":
      return InstagramStandaloneSettingsSchema.parse({
        __type: "instagram-standalone",
        post_type: instagramPostType(action),
      });
    case "tiktok":
      assertTikTokMediaCompatibility(action);
      return TikTokSettingsSchema.parse({
        __type: "tiktok",
        title: titleForProvider(action.title, "TikTok", 90),
        privacy_level: raw.privacyLevel,
        duet: raw.duet,
        stitch: raw.stitch,
        comment: raw.comments,
        autoAddMusic: raw.autoAddMusic,
        brand_content_toggle: raw.brandContent,
        brand_organic_toggle: raw.brandOrganic,
        video_made_with_ai: raw.videoMadeWithAi,
        content_posting_method: raw.contentPostingMethod,
      });
    case "youtube":
      if (action.media.mediaType !== "video") {
        block("Postiz YouTube scheduling requires video media");
      }
      return YouTubeSettingsSchema.parse({
        __type: "youtube",
        title: titleForProvider(action.title, "YouTube", 100, 2),
        type: raw.visibility,
        selfDeclaredMadeForKids: raw.madeForKids,
      });
    case "pinterest":
      if (action.media.mediaType !== "image") {
        block("Postiz Pinterest v1 scheduling requires image media");
      }
      return PinterestSettingsSchema.parse({ __type: "pinterest", board: raw.board });
    case "facebook":
      return FacebookSettingsSchema.parse({ __type: "facebook" });
    case "threads":
      return ThreadsSettingsSchema.parse({ __type: "threads" });
    case "linkedin":
      return LinkedInSettingsSchema.parse({ __type: "linkedin" });
    case "bluesky":
      return BlueskySettingsSchema.parse({ __type: "bluesky" });
  }
}

/**
 * Validates the complete frozen delivery descriptor before media is imported
 * into Postiz. This prevents an unsupported format or missing policy decision
 * from leaving an otherwise unused upload in the Postiz media library.
 */
export function validatePostizScheduleDescriptor(args: {
  action: PostizApprovedSchedule;
  settings: unknown;
}): PostizProviderSettings {
  const action = assertPostizScheduleIsSafelyFuture(args.action);
  const inputSettings = PostizScheduleSettingsInputSchema.parse(args.settings);
  return settingsForProvider(action, inputSettings);
}

/**
 * Maps the frozen approved snapshot and the Postiz-owned uploaded asset to the
 * exact documented scheduling payload. Unknown provider fields are rejected;
 * callers can never cause a "post now" request through this adapter.
 */
export function buildPostizScheduleRequest(args: {
  action: PostizApprovedSchedule;
  media: PostizUploadedMedia;
  settings: unknown;
}): PostizCreateScheduleRequest {
  const action = PostizApprovedScheduleSchema.parse(args.action);
  const media = PostizUploadedMediaSchema.parse(args.media);
  const settings = validatePostizScheduleDescriptor({ action, settings: args.settings });
  return PostizCreateScheduleRequestSchema.parse({
    type: "schedule",
    date: new Date(action.scheduledAt).toISOString(),
    shortLink: false,
    tags: [],
    posts: [{
      integration: { id: action.integrationId },
      value: [{ content: action.caption, image: [media] }],
      settings,
    }],
  });
}

function postizEndpoint(credentials: PostizCredentials, path: string): string {
  return `${credentials.origin}${POSTIZ_PUBLIC_API_PATH}${path}`;
}

async function readProviderBody(response: Response): Promise<unknown> {
  return await response.json().catch(() => null);
}

/**
 * Reconciles the frozen Media Engine account link with Postiz immediately
 * before importing media. This proves the integration still exists, is not
 * disabled, and is the platform that the approved snapshot named.
 */
export async function assertPostizIntegrationReady(args: {
  credentials: PostizCredentials;
  integrationId: string;
  provider: PostizProvider;
  request?: FetchImplementation;
}): Promise<void> {
  const integrationId = SafeIdentifierSchema.parse(args.integrationId);
  const provider = PostizProviderSchema.parse(args.provider);
  const response = await (args.request ?? fetch)(postizEndpoint(args.credentials, "/integrations"), {
    method: "GET",
    redirect: "error",
    headers: { authorization: args.credentials.apiKey },
  });
  const body = await readProviderBody(response);
  if (!response.ok) {
    throw new Error(`Postiz integration reconciliation returned HTTP ${response.status}`);
  }
  const integration = PostizIntegrationListSchema.parse(body).find((candidate) => candidate.id === integrationId);
  if (!integration) block("approved Postiz integration is no longer connected");
  if (integration.disabled) block("approved Postiz integration is disabled");
  if (integration.identifier !== provider) {
    block("Postiz integration no longer matches the approved platform");
  }
}

/**
 * Imports a controlled R2 render into the Postiz media store. The temporary
 * source URL stays only in worker memory and is not stored or logged.
 */
export async function uploadPostizMediaFromUrl(args: {
  credentials: PostizCredentials;
  sourceUrl: string;
  request?: FetchImplementation;
}): Promise<PostizUploadedMedia> {
  const sourceUrl = validatePostizUploadSourceUrl(args.sourceUrl);
  const response = await (args.request ?? fetch)(postizEndpoint(args.credentials, "/upload-from-url"), {
    method: "POST",
    redirect: "error",
    headers: {
      authorization: args.credentials.apiKey,
      "content-type": "application/json",
    },
    body: JSON.stringify({ url: sourceUrl }),
  });
  const body = await readProviderBody(response);
  if (!response.ok) {
    throw new Error(`Postiz upload returned HTTP ${response.status}`);
  }
  return PostizUploadedMediaSchema.parse(body);
}

/**
 * Creates exactly one future Postiz schedule after its render has been copied
 * into Postiz. There is no retry or replay support here: callers must treat a
 * network or response ambiguity as a manual reconciliation event.
 */
export async function createPostizSchedule(args: {
  credentials: PostizCredentials;
  request: PostizCreateScheduleRequest;
  expectedIntegrationId: string;
  fetchImplementation?: FetchImplementation;
}): Promise<{ postId: string; integrationId: string }> {
  const request = PostizCreateScheduleRequestSchema.parse(args.request);
  const expectedIntegrationId = SafeIdentifierSchema.parse(args.expectedIntegrationId);
  const response = await (args.fetchImplementation ?? fetch)(postizEndpoint(args.credentials, "/posts"), {
    method: "POST",
    redirect: "error",
    headers: {
      authorization: args.credentials.apiKey,
      "content-type": "application/json",
    },
    body: JSON.stringify(request),
  });
  const body = await readProviderBody(response);
  if (!response.ok) {
    throw new Error(`Postiz scheduling returned HTTP ${response.status}`);
  }
  const scheduled = PostizCreateScheduleResponseSchema.parse(body)[0];
  if (scheduled.integration !== expectedIntegrationId) {
    block("Postiz schedule receipt did not match the approved integration");
  }
  return { postId: scheduled.postId, integrationId: scheduled.integration };
}
